

我们通过查看ThreadPoolExecutor的源码可以看到他会默认的ｃａｔｃｈ住所有的异常，要是我们通过excute方法执行时，它是不会抛出异常的，
但是当我们通过submit方法提交任务并通过get方法获得返回结果的时候会看到抛出的异常．因为：

FutureTask是Future的实现而run方法的执行是在FutureTask内　而他捕获了所有的异常．

我们可以通过继承或者重写afterExecute这个方法来实现在线程执行的时候抛出异常然后处理．
